export const example = {
  query: "Example: The History of Sci-hub",
  results: [
    {
      abstract:
        "The website Sci-Hub enables users to download PDF versions of scholarly articles, including many articles that are paywalled at their journal’s site. Sci-Hub has grown rapidly since its creation in 2011, but the extent of its coverage has been unclear. Here we report that, as of March 2017, Sci-Hub’s database contains 68.9% of the 81.6 million scholarly articles registered with Crossref and 85.1% of articles published in toll access journals. We find that coverage varies by discipline and publisher, and that Sci-Hub preferentially covers popular, paywalled content. For toll access articles, we find that Sci-Hub provides greater coverage than the University of Pennsylvania, a major research university in the United States. Green open access to toll access articles via licit services, on the other hand, remains quite limited. Our interactive browser at https://greenelab.github.io/scihub allows users to explore these findings in more detail. For the first time, nearly all scholarly literature is available gratis to anyone with an Internet connection, suggesting the toll access business model may become unsustainable.",
      author: "Daniel Himmelstein, Ariel R Romero, Jacob Levernier, Thomas A. Munro, Stephen Reid McLaughlin, Bastian Greshake Tzovaras, Casey S. Greene",
      doi: "https://doi.org/10.7554/elife.32822",
      location: "PubMed",
      referencecount: 153,
      scihub_url: "https://sci-hub.se/10.7554/elife.32822",
      similarity: "barely related",
      source: "scihub",
      title: "Sci-Hub provides access to nearly all scholarly literature",
      url: "https://sci-hub.se/10.7554/elife.32822",
      year: 2018,
    },
    {
      abstract:
        "<ns4:p>Despite the growth of Open Access, potentially illegally circumventing paywalls to access scholarly publications is becoming a more mainstream phenomenon. The web service Sci-Hub is amongst the biggest facilitators of this, offering free access to around 62 million publications. So far it is not well studied how and why its users are accessing publications through Sci-Hub. By utilizing the recently released corpus of Sci-Hub and comparing it to the data of ~28 million downloads done through the service, this study tries to address some of these questions. The comparative analysis shows that both the usage and complete corpus is largely made up of recently published articles, with users disproportionately favoring newer articles and 35% of downloaded articles being published after 2013. These results hint that embargo periods before publications become Open Access are frequently circumnavigated using Guerilla Open Access approaches like Sci-Hub. On a journal level, the downloads show a bias towards some scholarly disciplines, especially Chemistry, suggesting increased barriers to access for these. Comparing the use and corpus on a publisher level, it becomes clear that only 11% of publishers are highly requested in comparison to the baseline frequency, while 45% of all publishers are significantly less accessed than expected. Despite this, the oligopoly of publishers is even more remarkable on the level of content consumption, with 80% of all downloads being published through only 9 publishers. All of this suggests that Sci-Hub is used by different populations and for a number of different reasons, and that there is still a lack of access to the published scientific record. A further analysis of these openly available data resources will undoubtedly be valuable for the investigation of Science publishing.</ns4:p>",
      author: "Bastian Greshake Tzovaras",
      doi: "https://doi.org/10.12688/f1000research.11366.1",
      location: "PubMed Central",
      referencecount: 52,
      scihub_url: "https://sci-hub.se/10.12688/f1000research.11366.1",
      similarity: "barely related",
      source: "scihub",
      title: "Looking into Pandora's Box: The Content of Sci-Hub and its Usage",
      url: "https://sci-hub.se/10.12688/f1000research.11366.1",
      year: 2017,
    },
    {
      abstract:
        "Late last week, I was contacted by an online contact asking if I would be interested in participating in an interview:- Do you want to be possibly interviewed by the Chronicle of Higher Ed about and Sci-hub? Being well aware of #icanhazpdf and Sci-Hub, I agreed. Sci-Hub is certainly a hot topic at the moment. \"n\" of #icanhazpdf tweet requests in the last 24 hours. 5 \"n\" of tweets about Sci-Hub in the last HOUR alone. 68 - ⓪ Grⓐhⓐm Steel (@McDawg) February 14, 2016 It wasn't practical to speaker with the reporter at that time so I emailed them back suggesting that they email me a few questions and I would respond. I heard back a few days later and got to work at formulating my responses. This took quite a bit longer than I had anticipated. The report at The Chronicle of Higher Education is due to be published week ending 19th February and I will link to it here as soon as I have found it. The Chronicle is a subscription publication. However, a fair percentage of articles can be read without a subscription and I hope that will be the case here. ++UPDATE++ The Chronicle article has now come out and you can read it in full here. From experience of doing interviews, I am fully aware that only a portion of what I wrote will be used. As such, I thought I would blog our Q&amp;A discussion in verbatim. QUESTION: In your article, you write that open access has become the new norm and social media is the tool driving it. I'm wondering, what is Sci-Hub's role in open access? Sci-Hub is not open access. Maybe it's a bit of grit in the oyster, helping to rock the boat. I completely agree with Dr Martin Eve who recently tweeted \"I can't condone and I don't think it's the answer, but it is a symptom of the problem. Pure open access business models would be immune to it\". QUESTION: Now that Elsevier is suing Sci-Hub there is much more attention drawn to Science piracy. In your opinion is Sci-Hub challenging the traditional pay to publish/pay to access model? Subscription journal workarounds have been around for many years. Sci-Hub is the most recent one and has received much attention over the last 12 months or so via social media, blog posts and broad media coverage. I'm not sure it's \"challenging\" these models per se (because it uses .edu proxies i.e., legitimate journal subscription accounts), but it has become an extremely effective way to access literature that is beyond the reach of most. Other than the legal aspects of the dispute with Elsevier, I sense there are also technology based ones. With regards to Sci-Hub generally, Richard Smith-Unna summarized matters succinctly in this tweet:- Let's face it, LibGen and SciHub are popular because they solve a problem Elsevier should have solved: disseminating knowledge. - ⓪ Rik Smith-Unna (@blahah404) June 10, 2015 QUESTION: Many librarians I've spoken to say that Science publishing is working off a broken system. Do you agree? If so, who is it up to to fix it? What will it take? There are several reasons that Science publishing is working off a broken system. The ongoing serials crisis. Addiction to Journal Impact Factor and most recently, expensive Article Processing Charges, e.g. here. However the publishing landscape continues to evolve. I would like to see Sciences, librarians and research funders taking more of a leading role in matters rather than the publishers. Some such as Björn Brembs even question the need for publishers at all ! QUESTION: Are you familiar with how Sci-Hub's model works? Does the fact that it uses university credentials to scrape papers from Elsevier and other journals put librarians who work at those university in an awkward position? Yes, I am aware of how the model works. This is not mentioned on the Sci-Hub platform, but is elsewhere such as the Wikipedia page about it. Many in the librarian community are aware of Sci-Hub and other methods of bypassing the modern interlibrary loan (ILL). A detailed paper titled Bypassing Interlibrary Loan Via Twitter: An Exploration of #icanhazpdf Requests by Gardner &amp; Gardner et al from 2015 is noteworthy. QUESTION: Is there a tension between Sciences and publishers? Is that how open access emerged? The open access movement traces its history at least back to the 1950s. Widespread access to the internet in the late 1990s and early 2000s fueled the movement. Post internet, open access was initially seen as a threat by traditional subscription based publishers and more recently, an opportunity. QUESTION: You've studied open access thoroughly. To you, what does the future look like for Sci-Hub? If it disappears, do you expect something else will take its place? The future of Sci-Hub is uncertain. It does have shades of the Napster era. See Napster, Udacity, and the Academy by Clay Shirky. That said, as The Library Loon states in her recent blog post Next moves in the Sci-Hub game \"Sci-Hub has come as close as anything to Napsterizing paywalled journals yet actually surviving the experience\". Pressure on the system will continue until we have full open access in place.",
      author: "Graham Steel",
      doi: "https://doi.org/10.15200/winn.145580.05844",
      location: "The Winnower",
      referencecount: 1,
      scihub_url: "https://doi.org/10.15200/winn.145580.05844",
      similarity: "barely related",
      source: "other",
      title: "Some thoughts about Sci-Hub",
      url: "https://doi.org/10.15200/winn.145580.05844",
      year: 2016,
    },
    {
      abstract:
        "Digital technologies have made access to and profit from scientific publications hotly contested issues. Debates over open access (OA), however, rarely extend from questions of distribution to questions of how OA is transforming the politics of Science knowledge production. This article argues that the movement towards OA rests on a relatively stable moral episteme that positions different actors involved in the economy of OA (authors, publishers, the general public), and most importantly, knowledge itself. The analysis disentangles the ontological and moral side of these claims, showing how OA changes the meaning of knowledge from a good in the economic, to good in the moral sense. This means OA can be theorized as the moral economy of digital knowledge production. Ultimately, using Boltanski and Thévenot's work on justification, the article reflects on how this moral economy frames the political subjectivity of actors and institutions involved in Science knowledge production.",
      author: "Jana Baćević, Chris Muellerleile",
      doi: "https://doi.org/10.1177/1368431017717368",
      location: "European Journal of Social Theory",
      referencecount: 39,
      scihub_url: "https://sci-hub.se/10.1177/1368431017717368",
      similarity: "barely related",
      source: "scihub",
      title: "The moral economy of open access",
      url: "https://sci-hub.se/10.1177/1368431017717368",
      year: 2017,
    },
    {
      abstract:
        "Accurate, reliable, and timely burn severity maps are necessary for planning, managing and rehabilitation after wildfires. This study aimed at assessing the ability of the Sentinel-2A satellite to detect burnt areas and separate burning severity levels. It also attempted to measure the spectral separability of the different bands and derived indices commonly used to detect burnt areas. A short investigation into the associated environmental variables present in the burnt landscape was also performed to explore the presence of any correlation. As a case study, a wildfire occurred in the Sierra de Gata region of the province of Caceres in North-Eastern Spain was used. A range of spectral indices was computed, including the Normalized Difference Vegetation Index (NDVI) and the Normalized Burn Ratio (NBR). The potential added value of the three new Red Edge bands that come with the Sentinel-2A MSI sensor was also used. The slope, aspect, fractional vegetation cover and terrain roughness were all derived to produce environmental variables. The burning severity was tested using the Spectral Angle Mapper (SAM) classifier. European Environment Agency's CORINE land cover map was also used to produce the land cover types found in the burned area. The Copernicus Emergency Management Service have produced a grading map for the fire using 0.5 m resolution Pleiades imagery, that was used as reference. Results showed a variable degree of correlation between the burning severity and the tested herein spectral indices. The visible part of the electromagnetic spectrum was not well suited to discern burned from unburned land cover. The NBRb12 (short-wave infrared 2 – SWIR2) produced the best results for detecting burnt areas. SAM resulted in a 73% overall accuracy in thematic mapping. None of the environmental variables appeared to have a significant impact on the burning severity. All in all, our study result showed that Sentinel-2 MSI sensor can be used to discern burnt areas and burning severity. However, further studies in different regions using the same dataset types and methods should be implemented before generalizing the results of the current study.",
      author: "Craig Amos, George P. Petropoulos, Konstantinos P. Ferentinos",
      doi: "https://doi.org/10.1080/01431161.2018.1519284",
      location: "International Journal of Remote Sensing",
      referencecount: 73,
      scihub_url: "https://sci-hub.se/10.1080/01431161.2018.1519284",
      similarity: "barely related",
      source: "scihub",
      title: "Determining the use of Sentinel-2A MSI for wildfire burning &amp; severity detection",
      url: "https://sci-hub.se/10.1080/01431161.2018.1519284",
      year: 2018,
    },
    {
      abstract:
        "Abstract Catastrophic failure of a tailings dam at an iron ore mine complex in Brumadinho, Brazil, on 25th January 2019 released 11.7 million m 3 of tailings downstream. Although reportedly monitored using an array of geotechnical techniques, the collapse occurred without any apparent warning. It claimed more than 200 lives and caused considerable environmental damage. Here we present the Intermittent Small Baseline Subset (ISBAS) technique on satellite-based interferometric synthetic aperture radar (InSAR) data to assess the course of events. We find that parts of the dam wall and tailings were experiencing deformation not consistent with consolidation settlement preceding the collapse. Furthermore, we show that the timing of the dam collapse would have been foreseeable based on this observed precursory deformation. We conclude that satellite-based monitoring techniques may help mitigate similar catastrophes in the future.",
      author: "Stephen Grebby, Andrew Sowter, Jon Gluyas, D. G. Toll, David G. Gee, Ahmed Athab, Renoy Girindran",
      doi: "https://doi.org/10.1038/s43247-020-00079-2",
      location: "Communications Earth & Environment",
      referencecount: 58,
      scihub_url: "https://sci-hub.se/10.1038/s43247-020-00079-2",
      similarity: "barely related",
      source: "scihub",
      title: "Advanced analysis of satellite data reveals ground deformation precursors to the Brumadinho Tailings Dam collapse",
      url: "https://sci-hub.se/10.1038/s43247-020-00079-2",
      year: 2021,
    },
  ],
  summary: {
    cot: "local",
    sum: "Sci-Hub, launched in 2011 by Alexandra Elbakyan, has emerged as a prominent solution for accessing scholarly articles that are typically behind paywalls. This digital platform enables users to download PDFs of scientific literature, facilitating access to publications that many cannot afford. As of March 2017, it was reported that Sci-Hub's database held over 68 million articles, comprising a significant portion of the total scholarly literature indexed by Crossref. The service has sparked extensive debate surrounding Science publishing models, particularly in the context of Open Access and copyright infringement. Critics argue that Sci-Hub highlights the systemic issues in Science publishing, where the high costs of accessing scholarly work limit equitable access to knowledge. For further reading on the impact and usage patterns of Sci-Hub, please refer to the study titled \"Looking into Pandora's Box: The Content of Sci-Hub and its Usage,\" available at [F1000Research](https://sci-hub.se/10.12688/f1000research.11366.1).",
  },
};